# Generated by Django 4.2.5 on 2023-09-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recordOfInvention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('name_of_invention', models.CharField(default='', max_length=20)),
                ('problem_it_solves', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
