# Generated by Django 4.2.5 on 2023-10-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_step1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='step1',
            new_name='stepOne',
        ),
    ]
