# Generated by Django 4.2.5 on 2023-10-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_step1_stepone'),
    ]

    operations = [
        migrations.CreateModel(
            name='stepTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('p1name1', models.CharField(default='', max_length=1200)),
                ('p1name2', models.CharField(default='', max_length=1200)),
                ('p1name3', models.CharField(default='', max_length=1200)),
                ('p1name4', models.CharField(default='', max_length=1200)),
                ('p1age1', models.CharField(default='', max_length=1200)),
                ('p1age2', models.CharField(default='', max_length=1200)),
                ('p1age3', models.CharField(default='', max_length=1200)),
                ('p1age4', models.CharField(default='', max_length=1200)),
                ('p1comment1', models.CharField(default='', max_length=1200)),
                ('p1comment2', models.CharField(default='', max_length=1200)),
                ('p1comment3', models.CharField(default='', max_length=1200)),
                ('p1comment4', models.CharField(default='', max_length=1200)),
                ('p2name1', models.CharField(default='', max_length=1200)),
                ('p2name2', models.CharField(default='', max_length=1200)),
                ('p2name3', models.CharField(default='', max_length=1200)),
                ('p2name4', models.CharField(default='', max_length=1200)),
                ('p2age1', models.CharField(default='', max_length=1200)),
                ('p2age2', models.CharField(default='', max_length=1200)),
                ('p2age3', models.CharField(default='', max_length=1200)),
                ('p2age4', models.CharField(default='', max_length=1200)),
                ('p2comment1', models.CharField(default='', max_length=1200)),
                ('p2comment2', models.CharField(default='', max_length=1200)),
                ('p2comment3', models.CharField(default='', max_length=1200)),
                ('p2comment4', models.CharField(default='', max_length=1200)),
                ('p3name1', models.CharField(default='', max_length=1200)),
                ('p3name2', models.CharField(default='', max_length=1200)),
                ('p3name3', models.CharField(default='', max_length=1200)),
                ('p3name4', models.CharField(default='', max_length=1200)),
                ('p3age1', models.CharField(default='', max_length=1200)),
                ('p3age2', models.CharField(default='', max_length=1200)),
                ('p3age3', models.CharField(default='', max_length=1200)),
                ('p3age4', models.CharField(default='', max_length=1200)),
                ('p3comment1', models.CharField(default='', max_length=1200)),
                ('p3comment2', models.CharField(default='', max_length=1200)),
                ('p3comment3', models.CharField(default='', max_length=1200)),
                ('p3comment4', models.CharField(default='', max_length=1200)),
                ('p4name1', models.CharField(default='', max_length=1200)),
                ('p4name2', models.CharField(default='', max_length=1200)),
                ('p4name3', models.CharField(default='', max_length=1200)),
                ('p4name4', models.CharField(default='', max_length=1200)),
                ('p4age1', models.CharField(default='', max_length=1200)),
                ('p4age2', models.CharField(default='', max_length=1200)),
                ('p4age3', models.CharField(default='', max_length=1200)),
                ('p4age4', models.CharField(default='', max_length=1200)),
                ('p4comment1', models.CharField(default='', max_length=1200)),
                ('p4comment2', models.CharField(default='', max_length=1200)),
                ('p4comment3', models.CharField(default='', max_length=1200)),
                ('p4comment4', models.CharField(default='', max_length=1200)),
                ('other_notes', models.CharField(default='', max_length=1200)),
                ('describe_problem', models.CharField(default='', max_length=1200)),
                ('specific_solution', models.CharField(default='', max_length=1200)),
            ],
        ),
        migrations.AlterField(
            model_name='recordofinvention',
            name='name_of_invention',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AlterField(
            model_name='recordofinvention',
            name='problem_it_solves',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AlterField(
            model_name='stepone',
            name='identify_problems',
            field=models.CharField(default='', max_length=1200),
        ),
    ]
