# Generated by Django 4.2.5 on 2023-10-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_steptwo_alter_recordofinvention_name_of_invention_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stepThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('factors', models.CharField(default='', max_length=1200)),
                ('ways_to_solve', models.CharField(default='', max_length=1200)),
                ('research', models.CharField(default='', max_length=1200)),
                ('difference', models.CharField(default='', max_length=1200)),
            ],
        ),
    ]
