# Generated by Django 4.2.5 on 2023-10-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_stepthree'),
    ]

    operations = [
        migrations.CreateModel(
            name='stepFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('blueprint', models.ImageField(blank=True, null=True, upload_to='')),
                ('teacher_name', models.CharField(default='', max_length=1200)),
                ('teacher_sign', models.CharField(default='', max_length=1200)),
                ('date', models.CharField(default='', max_length=1200)),
                ('i1expert', models.CharField(default='', max_length=1200)),
                ('i1credentials', models.CharField(default='', max_length=1200)),
                ('i1identified', models.CharField(default='', max_length=1200)),
                ('i1problemface', models.CharField(default='', max_length=1200)),
                ('i2expert', models.CharField(default='', max_length=1200)),
                ('i2credentials', models.CharField(default='', max_length=1200)),
                ('i2identified', models.CharField(default='', max_length=1200)),
                ('i2problemface', models.CharField(default='', max_length=1200)),
                ('i3expert', models.CharField(default='', max_length=1200)),
                ('i3credentials', models.CharField(default='', max_length=1200)),
                ('i3identified', models.CharField(default='', max_length=1200)),
                ('i3problemface', models.CharField(default='', max_length=1200)),
                ('sol_design_problem', models.CharField(default='', max_length=1200)),
                ('green_sol', models.CharField(default='', max_length=1200)),
            ],
        ),
    ]
