# Generated by Django 4.2.5 on 2023-10-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_stepfour'),
    ]

    operations = [
        migrations.CreateModel(
            name='stepFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('materials', models.CharField(default='', max_length=1200)),
                ('findings', models.CharField(default='', max_length=1200)),
                ('credit', models.CharField(default='', max_length=1200)),
            ],
        ),
    ]
