# Generated by Django 4.2.5 on 2023-10-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_stepfive'),
    ]

    operations = [
        migrations.CreateModel(
            name='stepSix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(default='', max_length=1200)),
                ('prototype_pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
