# Generated by Django 4.2.5 on 2023-10-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_stepseven'),
    ]

    operations = [
        migrations.CreateModel(
            name='stepEight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('nameinvention', models.CharField(default='', max_length=1200)),
                ('benefits', models.CharField(default='', max_length=1200)),
                ('price', models.CharField(default='', max_length=1200)),
                ('customer_age', models.CharField(default='', max_length=1200)),
                ('customer_gender', models.CharField(default='', max_length=1200)),
                ('customer_education', models.CharField(default='', max_length=1200)),
                ('customer_house', models.CharField(default='', max_length=1200)),
                ('customer_marital', models.CharField(default='', max_length=1200)),
                ('other_notes', models.CharField(default='', max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='surveyLogbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('things_enjoyed', models.CharField(default='', max_length=1200)),
                ('thanking', models.CharField(default='', max_length=1200)),
                ('difficulty', models.CharField(default='', max_length=1200)),
                ('future', models.CharField(default='', max_length=1200)),
            ],
        ),
    ]
