# Generated by Django 4.2.5 on 2023-10-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_statementoforiginality'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementoforiginality',
            name='date1',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='statementoforiginality',
            name='date2',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='statementoforiginality',
            name='date3',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='statementoforiginality',
            name='date4',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='statementoforiginality',
            name='date5',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='statementoforiginality',
            name='date6',
            field=models.CharField(default='', max_length=1200),
        ),
    ]
