# Generated by Django 4.2.5 on 2023-10-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_statementoforiginality_date1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('note_title', models.CharField(default='', max_length=1200)),
                ('note_desc', models.CharField(default='', max_length=1200)),
            ],
        ),
    ]
