# Generated by Django 4.2.5 on 2023-10-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepeight',
            name='buy',
            field=models.CharField(default='', max_length=1200),
        ),
    ]
